use_frameworks!

platform :ios, '12.0'

target 'NaverMapCluster_Example' do
  pod 'SnapKit'
  pod 'NaverMapCluster', :path => '../'

  target 'NaverMapCluster_Tests' do
    inherit! :search_paths

    
  end
end
