# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ClusterExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'SnapKit'
  pod 'NaverMapCluster', :git => 'https://github.com/manunite/NaverMapCluster.git', :tag => '0.1.5'

end
